secrets:
        secret_name : "twillio_creds"
        region_name : "us-west-1"
college:
        name: "WhatsAMatterU"
chatbot:
        name: "DnD DM"
twillio:
        phone_number: "+18583303617"


#chatbot:
        #name: "Bianca Del Rio"
